# Generated by Django 5.1.5 on 2025-02-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment_mentions_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='can_delete_files',
            field=models.BooleanField(default=False),
        ),
    ]
