# Generated by Django 5.1.5 on 2025-02-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectrole_permissions_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='permissions',
        ),
    ]
