# Generated by Django 5.1.5 on 2025-02-25 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_role_permissions'),
        ('projects', '0007_alter_projectrole_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='permissions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='projects.projectpermission'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together={('user', 'project', 'role')},
        ),
    ]
