# Generated by Django 4.2.19 on 2025-02-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectrole_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_added', 'Added to a Project'), ('role_assigned', 'Role Assigned'), ('mentioned', 'Mentioned in a Task'), ('member_added', 'Team Member Added'), ('role_changed', 'Role Changed')], default='project_added', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
