# Generated by Django 4.2.19 on 2025-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_notification_notification_type_notification_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='can_delete_project',
            field=models.BooleanField(default=False),
        ),
    ]
