# Generated by Django 5.1.5 on 2025-02-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('projects', '0004_rename_description_project_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_tasks', models.BooleanField(default=False)),
                ('can_edit_tasks', models.BooleanField(default=False)),
                ('can_delete_tasks', models.BooleanField(default=False)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.projectrole')),
            ],
        ),
    ]
