# Generated by Django 5.1.5 on 2025-02-14 19:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_role_permissions'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together={('user', 'project', 'role')},
        ),
    ]
