# Generated by Django 5.1.5 on 2025-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='icon',
        ),
        migrations.AddField(
            model_name='feature',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Upload an SVG file', null=True, upload_to='feature_icons/'),
        ),
        migrations.AddField(
            model_name='feature',
            name='svg_icon',
            field=models.TextField(blank=True, help_text='Inline SVG markup for custom icons', null=True),
        ),
    ]
