# Generated by Django 5.1.5 on 2025-01-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_feature_icon_feature_icon_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
    ]
