# Generated by Django 5.1.5 on 2025-02-24 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectpermission_can_delete_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='permissions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='projects.projectpermission'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='project_role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='projects.projectrole'),
        ),
    ]
