# Generated by Django 5.1.5 on 2025-02-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
    ]
